### ISSUE TITLE
compilation issue in usr/vtltape.c

### ISSUE THREAD

**Issue by davrosyoung** [markh794/mhvtl#116]
Since last week (when it compiled just fine), the following compilation error has crept into usr/vtltape.c;

cc -Wall -Wshadow -g -O2 -D_LARGEFILE64_SOURCE  -I../kernel -I../ccan -DMHVTL_VERSION=\"1.7.1-git-master\" -D_GNU_SOURCE -DMHVTL_DEBUG -DMHVTL_HOME_PATH=\"/opt/mhvtl\" -DMHVTL_CONFIG_PATH=\"/etc/mhvtl\" -DSYSTEMD_SERVICE_DIR=\"/lib/systemd/system\"   -c -o vtltape.o vtltape.c
vtltape.c: In function ‘processMessageQ’:
vtltape.c:1534:7: error: ‘fg’ undeclared (first use in this function)
 1534 |       fg = TA_MEDIA_NOT_SUPPORTED;
      |       ^~
vtltape.c:1534:7: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [<builtin>: vtltape.o] Error 1
make[1]: Leaving directory '/home/somebody/projects/mhvtl/usr'
make: *** [Makefile:37: usr] Error 2

The fix I've made locally is to declare the fg variable as it is declared elsewhere in this source file (such as in the loadTape function) as uint64_t fg = TA_NONE; within the processMessageQ function.

**Comment by davrosyoung** [comment]
A pull request has been raised to remedy this; https://github.com/markh794/mhvtl/pull/117

**Comment by markh794** [comment]
Merged - many thanks

**Comment by davrosyoung** [comment]
Mark,

I use your mhvtl library a *lot*. Very very small contribution back from me.

Regards,

David
