### ISSUE TITLE
Tape load no longer working for STK-L700 emulation

### ISSUE THREAD

**Issue by DaveAtFraud** [markh794/mhvtl#120]
mtx status shows everything good and I can do a load to load a virtual tape:

root@rocky9mate ~]# mtx -f /dev/sg9 load 1 0
Drive 0 Full (Storage Element 10 loaded)
[root@rocky9mate ~]# mtx -f /dev/sg9 status
  Storage Changer /dev/sg9:4 Drives, 41 Slots ( 4 Import/Export )
Data Transfer Element 0:Full (Storage Element 10 Loaded):VolumeTag = E01010L4

But mt -f /dev/nst0 tell and other "reasonable" tape commands fail to find a tape:

[root@rocky9mate ~]# mt -f /dev/nst0 tell
/dev/nst0: No medium found
[root@rocky9mate ~]# mt -f /dev/st0 tell
/dev/st0: No medium found

But mtx status still says its there:

[root@rocky9mate ~]# mtx -f /dev/sg9 status
  Storage Changer /dev/sg9:4 Drives, 41 Slots ( 4 Import/Export )
Data Transfer Element 0:Full (Storage Element 1 Loaded):VolumeTag = E01001L4                            
Data Transfer Element 1:Empty
Data Transfer Element 2:Empty
Data Transfer Element 3:Empty
      Storage Element 1:Empty

System is Rocky Linux with kernel:

[root@rocky9mate ~]# uname -a
Linux rocky9mate.local.davenjudy.org 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

mhVTL is 1.7.

I'm running amanda and I get:

[amandabackup@rocky9mate ~]$ amcheck DailySet1
Amanda Tape Server Host Check
-----------------------------
NOTE: Holding disk '/var/lib/amanda/dumps': 32280576 KB disk space available, using 32178176 KB
slot 1: Tape device /dev/nst0 is not ready or is empty
slot 2: Tape device /dev/nst0 is not ready or is empty

which is consistent with the mt "tell" saying no medium found.  mhVTL and amanda were working fine on this system a couple of kernels ago.  Need to find my last working kernel.

**Comment by markh794** [comment]
Are you able to provide the output of 'lsscsi -g' please.
I note that you are attempting to load a LTO-4 media - I was curious as to the type of drive you are loading LTO-4 media into.
Also the syslog / messages file which covers the mount time (a couple minutes before/after) would be nice too.

A recent patch did change the check while mounting media - which was a long time bug.

**Comment by markh794** [comment]
patch I was referencing in above comment is : 74185e3c7a91fc5353cd77359c444a21b1d99466 (Clean up after media mount failure) 2023-07-07

**Comment by DaveAtFraud** [comment]
Quick follow-up and then close.  The root problem is most distro kernels are now compiled with asynchronous discovery in order to speed up boot time.  This results in SCSI device assignment being 1) somewhat random and 2) possibly changing at each reboot.  Opened a new bug with the amanda folks since they will need to come up with a mechanism for assigning tape drives that doesn't rely on /dev/nst0 being the first drive in the first changer.

**Comment by gonzoleeman** [comment]
Udev rules can fix that. --Lee-Man DuncanSent from my iPhone, dudeOn Aug 1, 2023, at 7:24 PM, David G. Miller ***@***.***> wrote:﻿
Quick follow-up and then close.  The root problem is most distro kernels are now compiled with asynchronous discovery in order to speed up boot time.  This results in SCSI device assignment being 1) somewhat random and 2) possibly changing at each reboot.  Opened a new bug with the amanda folks since they will need to come up with a mechanism for assigning tape drives that doesn't rely on /dev/nst0 being the first drive in the first changer.

**Comment by markh794** [comment]
Re: udev rules

See the mhvtl/scripts/build-persistent-tape-rules.sh as an example
or run the mentioned script and redirect the output into your tape udev rules.
e.g.

scripts/build-persistent-tape-rules.sh > /etc/udev/rules.d/70-persistent-tape.rules

And reload the udev rules.

or don't use /dev/nst* but the /dev/tape/by-id/* for persistent names
