### ISSUE TITLE
The  flags are wrong in the long form response of read position?

### ISSUE THREAD

**Issue by neepher** [markh794/mhvtl#129]
I'm using READ POSITION command with service action 6 to request current position of tape, but I found the MPU flag and the LONU flag are error.

Accoring to the SSC specification:
> A mark position unknown ( MPU ) bit of one specifies the file number and set number are not known or accurate
reporting is not currently available. A MPU bit of zero specifies the FILE NUMBER and SET NUMBER fields contain valid
position information.

> A logical object number unknown ( LONU ) bit of one specifies the logical object number or partition number are not
known or accurate reporting is not currently available. A LONU bit of zero specifies the LOGICAL OBJECT NUMBER and
PARTITION NUMBER fields contain valid position information.

Now, my tape library is :
```shell
Vendor ID: 'IBM     '
Product ID: 'ULT3580-TD5     '
Revision: '252D'
```

The result is:
* LONU flag is set to 1, but the LOGICAL OBJECT NUMBER is right
* MPU flag is set to 0, but the FILE NUMBER and SET NUMBER fields are invalid

```shell
sg_raw -r 1k /dev/sg26 34 06 00 00 00 00 00 00 00 00
SCSI Status: Good 

Received 32 bytes of data:
 00     04 00 00 00 00 00 00 00  00 00 00 00 00 00 00 02    ................
 10     00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00    ................


sg_raw -r 1k /dev/sg26 34 00 00 00 00 00 00 00 00 00
SCSI Status: Good 

Received 20 bytes of data:
 00     30 00 00 00 00 00 00 02  00 00 00 02 00 00 00 00    0...............
 10     00 00 00 00                                         ....
```

Is this a bug ?

**Comment by markh794** [comment]
Many thanks for bring this to my attention. I'll look into this shortly.

**Comment by markh794** [comment]
Reviewing the READ POSITION, I see many failings with regards to the standards.
Currently working on improvements.

**Comment by markh794** [comment]
Commit c2541978727aba2f3bbb9a3052dc98943406923e should resolve this issue. The READ POSITION should return the correct data now.
