### ISSUE TITLE
capacity limit not work

### ISSUE THREAD

**Issue by hrchu** [markh794/mhvtl#13]
```
# dump_tape -f E01001L4
Media density code: 0x46
Media type code   : 0x08
Media description : Ultrium 4/16T
Tape Capacity     : 524288000 (500 MBytes)
Media type        : Normal data
Media             : read-write
Remaining Tape Capacity : 524288000 (500 MBytes)
Total num of filemarks: 13
Segmentation fault (core dumped)
```
```
# du -h /opt/mhvtl/E01001L4/
755M    /opt/mhvtl/E01001L4/
```

**Comment by markh794** [comment]
What / how did you write the data to this 'tape' ?
Can you please provide a "du -sh /opt/mhvtl/E01001L4/*" (so I can see the size of each of the files).
The 'data' file should be limited to 500M +/- a block.
The 'meta data' for each block is 512 bytes. Hence, if you have specified a very small block size, the meta data can account for much of the space.
Specifying a 512k block size results in a 1:1000 ratio.
Specifying a 512byte block size results in a 1:1 ratio.

The 'segfault' is another issue. Do you have an associated core file ?
What version of the mhVTL are you using ?

**Comment by hrchu** [comment]
1. ```truncate -s 1G 1G; for i in {1..10}; do tar cf /dev/nst5 1G;done```
2. Wired,
```
# du -h /opt/mhvtl/E01002L4/*
69M     /opt/mhvtl/E01002L4/data
513M    /opt/mhvtl/E01002L4/indx
4.0K    /opt/mhvtl/E01002L4/meta
```
3. I don't see any core dump file. How can I get it?
4. I install mhVTL from the master branch.

The problem is related to sparse file maybe?

**Comment by markh794** [comment]
OK - you have provided the info from a different "tape" - but as you can see, in this instance, the 'indx file is 513M, while the data is still only 69M.. The size is based around the 'data' file, the meta and indx is *not* taken into account.
I would strongly recommend you add a block size to tar - it will improve the performance significantly. Especially if you go to use real tape drives.
If you are using LTO - I would suggest a minimum block size of 32k, most backup programes default to 64k. A range between 64k - 512k is typical. Do *not* set 'fixed block size' on the tape device (using the mt command). Leave it using 'variable block size' - much more efficient for sequential (tape) devices.

re: core file.
Confirm 'ulimit -a' -> Max core size is unlimited. Then start the mhVTL daemons from that shell.
Re-run the dump_tape -f .... -> if it segfaults, it should produce a core (potentially named either 'core' or 'core.<pid>') Depending on the way you have set your machine up.

**Comment by hrchu** [comment]
I will use block size you recommend and not use sparse file to prevent the problem. Thanks.
