### ISSUE TITLE
Enhancement idea: update vtlcmd to show the commit number and date released

### ISSUE THREAD

**Issue by rohr22** [markh794/mhvtl#132]
I was wondering if there is an easy way to tell what the commit version is for a particular source tree of mhvtl. I recently extracted the source code corresponding to commit 1579. Is there any way to tell this from a mhvtl command-line tool? I would think it would be useful if the vtlcmd or another command were updated to show this. Currently, I can get the mhvtl version with vtlcmd:

```
vtlcmd -v
Version: 1.7.1
```

However, it would be really nice if it showed the commit number and date corresponding to this, for example:
```
vtlcmd -v
Version: 1.7.1, commit version: 1579, date created: 2024/05/07
```

Thank you,
Peter

**Comment by rohr22** [comment]
I think this might not be so easy to get the commit number since that is added by github, but maybe the date could be easier to show.

**Comment by markh794** [comment]
Sounds like a good thing to add.. Let me work on it.

**Comment by markh794** [comment]
In the above example - is 'date created' - the git commit date, or the compile date of the binary itself ?

**Comment by rohr22** [comment]
It is the git commit date.

**Comment by markh794** [comment]
Is this the type of format you're interested in ?
`
$ vtlcmd -V
`
`
Version: 1.7.1, commit: 9548ed2, commit date: 2024-05-15T10:27:28+10:00
`

**Comment by rohr22** [comment]
Yeah, that should work.

**Comment by rohr22** [comment]
I guess you could shorten to something like this:
```
$ vtlcmd -V
Version: 1.7.1, commit: 9548ed2 (2024-05-15T10:27:28+10:00)

```

**Comment by rohr22** [comment]
Or maybe even:
```
$ vtlcmd -V
Version: 1.7.1, commit: 9548ed2 2024-05-15T10:27:28+10:00
```

**Comment by gonzoleeman** [comment]
On May 16, 2024, at 4:42 PM, Peter ***@***.***> wrote:
> 
> 
> Or maybe even:
> 
> $ vtlcmd -V
> Version: 1.7.1, commit: 9548ed2 2024-05-15T10:27:28+10:00

Personally i think this is difficult to do, and not really needed. That’s what tags are for.

To do this, as suggested, you’d need to commit it first, then build the binary. And it assumes git, correct? Why does the average user want to know the git commit id?

Just my opinion. :)
— 
Lee Duncan

**Comment by markh794** [comment]
I'm targeting the additional git version stuff for non RPM builds only. Let's see how it works out :)

**Comment by markh794** [comment]
Commit d6da2cb5155033837ba7a20107942e08431bb042 added this info. But only if built from git source. RPM based builds should (still) only report the RPM build version - e.g. 1.7.1

**Comment by rohr22** [comment]
Thank you very much for making these changes! I'll try it out soon and let you know what I think.

**Comment by rohr22** [comment]
Hi, Mark. I tried out the latest code and vtlcmd -V appears to have the same output as before. When I did the make, I saw stuff like this:

make[1]: Entering directory '/opt/vtl.source/commit_1582/mhvtl-master/usr'
cc -Wall -Wshadow -g -O2 -D_LARGEFILE64_SOURCE  -I../kernel -I../ccan -DMHVTL_VERSION=\"1.7.1\" -DMHVTL_GITDATE=\"\" `-DMHVTL_GITHASH=\"\"` -D_GNU_SOURCE -DMHVTL_DEBUG -DMHVTL_HOME_PATH=\"/opt/vtl\" -DMHVTL_CONFIG_PATH=\"/etc/mhvtl\" -DSYSTEMD_SERVICE_DIR=\"/lib/systemd/system\" -c -fpic log.c

The MHVTL_GITHASH value is "". I downloaded the latest mhvtl code (commit 1582) by clicking on the "Code" link at https://github.com/markh794/mhvtl and then clicking on "Download ZIP" from the HTTPS tab. What is the correct way to download the code so that MHVTL_GITHASH gets set properly? I looked at how it is set and config.mk has:

`GITHASH ?= $(if $(shell test -d $(TOPDIR)/.git && echo 1),commit:\ $(shell git show -s --format=%h))`

I don't have a .git directory under the top directory. Instead I have a .github directory.

Thank you,
Peter

**Comment by rohr22** [comment]
I think I figured out how to download it so that vtlcmd -V shows the fuller version information. I just need to run "git clone https://github.com/markh794/mhvtl.git" and build from the source tree created from that.

**Comment by markh794** [comment]
> Hi, Mark. I tried out the latest code and vtlcmd -V appears to have the same output as before. When I did the make, I saw stuff like this:
> 
> make[1]: Entering directory '/opt/vtl.source/commit_1582/mhvtl-master/usr' cc -Wall -Wshadow -g -O2 -D_LARGEFILE64_SOURCE -I../kernel -I../ccan -DMHVTL_VERSION="1.7.1" -DMHVTL_GITDATE="" `-DMHVTL_GITHASH=\"\"` -D_GNU_SOURCE -DMHVTL_DEBUG -DMHVTL_HOME_PATH="/opt/vtl" -DMHVTL_CONFIG_PATH="/etc/mhvtl" -DSYSTEMD_SERVICE_DIR="/lib/systemd/system" -c -fpic log.c
> 
> The MHVTL_GITHASH value is "". I downloaded the latest mhvtl code (commit 1582) by clicking on the "Code" link at https://github.com/markh794/mhvtl and then clicking on "Download ZIP" from the HTTPS tab. What is the correct way to download the code so that MHVTL_GITHASH gets set properly? I looked at how it is set and config.mk has:
> 
> `GITHASH ?= $(if $(shell test -d $(TOPDIR)/.git && echo 1),commit:\ $(shell git show -s --format=%h))`
> 
> I don't have a .git directory under the top directory. Instead I have a .github directory.
> 
> Thank you, Peter

Let me try that method and see if I can include check for .github dir :)
