### ISSUE TITLE
LTO8

### ISSUE THREAD

**Issue by darkphase** [markh794/mhvtl#30]
Is it possible to add LTO8 support?

**Comment by markh794** [comment]
Short answer : Yes..
Longer answer: I could not find the LTO-8 SCSI Reference guide last time I looked, This time I've found a copy, so updating to support the IBM Ultrium-8 should be simple. Although there is comments regarding 'M8' media type which may take a little more work.
LTFS support will still be missing..

**Comment by darkphase** [comment]
Yes LTO 7M cartridges can be formatted to support higher volumes but since LTO9 is already on its way it is just a sad nuisance that nobody uses.
How much of a work do you think adding LTFS support... Does LTFS really a hardware issue?

**Comment by markh794** [comment]
LTFS...
I get about 1 - 2 queries for this every 12mts or so.. (i.e. not a huge demand)
There are a couple of road-blocks
 - Lack of s/w to test LTFS (not really an excuse...)
 - Requires multiple partitions on the 'tape'. A new back-end format would be required. This again is not a big issue in itself.
 - A bigger hurdle is I do not have access to a real environment to compare against.
 - The biggest hurdle is the available free time to implement the feature.

**Comment by markh794** [comment]
I have a patch which has passed initial testing (Backup & Verify test using NetBackup 8.1.2).
I shall do some more sanity checks and most likely push it into GitHub early next week.

**Comment by markh794** [comment]
I've just pushed out this patch. Fundamentally no different to LTO6 -> LTO7 patch.

**Comment by markh794** [comment]
I'll close out this as complete. Feel free in new bug report if something doesn't quite work out
