### ISSUE TITLE
wrong denstity values for LTO-8

### ISSUE THREAD

**Issue by khambrecht** [markh794/mhvtl#55]
with #30 LTO-8 support was introduced. However, the LTO-8 emulation uses wrong density values. Looks like the some of the LTO-7 values were just copied for LTO-8, but LTO-8 uses different values for bits-per-mm, tracks and capacity.

Applies to both emulations, ult3580_pm.c and hp_ultrium_pm.c

See IBM Ultrium reference, chapter 5.2.24.1.2 Density information, on page 134.

**Comment by khambrecht** [comment]
Link to IBM reference:

https://www.ibm.com/support/pages/sites/default/files/support/ssg/ssgdocs.nsf/0/4d430d4b4e1f09b18525787300607b1d/%24FILE/LTO%20SCSI%20Reference%20%28EXTERNAL%20-%2020171024%29.pdf

**Comment by markh794** [comment]
Many thanks for the doco link & bug report. I’ll look into it early next week

**Comment by markh794** [comment]
I've just updated the density code via : a7d72eee5ab27523fda4ec30ba53410f9b494f96

**Comment by khambrecht** [comment]
thanks for updating. However, there is a little mistake in your changes. LTO-8 is fine now. But LTO-7 values used to be valid before the change, but are wrong now. These are now the values for the special LTO-8 Type M (i.e. an LTO-7 Media initialized in an LTO-8 Drive to gain higher capacity).

So correct values are:

LTO-7 (LTO-L7): 
* bits per mm: 19107
* media width: 127
* tracks: 3584
* capacity: 6000000

LTO-8 Type M (LTO-M8): 
* bits per mm: 19107
* media width: 127
* tracks: 5376
* capacity: 9000000

LTO-8 (LTO-L8): 
* bits per mm: 20669
* media width: 127
* tracks: 6656
* capacity: 12000000
