### ISSUE TITLE
resp_spout() - issue with pointer check?

### ISSUE THREAD

**Issue by scsirob** [markh794/mhvtl#56]
In this line you check if a personality module has an update_encryption_mode() function before calling it:
https://github.com/markh794/mhvtl/blob/a7d72eee5ab27523fda4ec30ba53410f9b494f96/usr/vtltape.c#L1611

It appears that the update_encryption_mode() function will only be called when it points to NULL. Which will no doubt cause a crash? If the pointer is initialized to the proper personality module, it will never be called, no?

**Comment by markh794** [comment]
Good spotting. I'll fix ASAP :)
Did you encounter the null pointer in practice or code review ? (Just curious)

**Comment by scsirob** [comment]
It was during code review. I'm trying to wrap my head around the whole encryption process for my project and was looking at what you had come up with. I have not seen any software in the open that sends a SPOUT to devices that do not support encryption.
With this fix you'll find out if there are any issues with your update_encryption_mode() routines ;)

**Comment by markh794** [comment]
Like a lot of this code - Once NetBackup was happy with the functionality, I moved onto other areas that needed more attention. One of these days, I do plan on sitting down with the t10 doco and filling in the rest of the blanks - we'll see how the 'free time' concept works out in the real world.
