### ISSUE TITLE
Update mhvtl to have support for VERIFY_6 with vbf=1

### ISSUE THREAD

**Issue by rohr22** [markh794/mhvtl#76]
On our project we would like mhvtl to be updated to offer support for VERIFY_6 with vbf=1. See https://www.ibm.com/support/pages/system/files/inline-files/LTO%20SCSI%20Reference%20(EXTERNAL-18Aug2021)_1.pdf

Thank you,
Peter

**Comment by markh794** [comment]
I've just committed a patch for verify_6 (including Verify By Filemarks). (b548b4d3536fd02969f1f7091654e8bf81f9ce18)
I've do not have access to any software that depends on this feature - Are you able to check its functionality ?

**Comment by rohr22** [comment]
Hi, Mark. Thanks for providing the patch. Do you provide logical block protection support? I tried to write to an mhvtl tape that we marked as having block protection. However, when I tried to write to an mhvtl volume, I got an error that block protection was not supported. Another one of my colleagues understood that you supported this, but from the results I am seeing I am not sure if this is true.

At this point I cannot yet verify that your new code offers VERIFY_6 support since our application won't let me write to a mhvtl tape since it determined that it doesn't offer block protection.

**Comment by rohr22** [comment]
Actually, I was able to try out the patch. I created a tape volume without block protection. I wrote several files to the tape. When I ran a tool we use to verify the tape, I got error output which showed a problem with the last file. However, this was the same behavior seen when using real tape. I think we have an issue with our application. When I tried verifying a tape on a system without your patch, I got different error output which indicated that none of the files could be verified. So I think your new code may be working properly. I will be able to do more tests once we fix the problem on our end.

But I am still wondering if you provide support for block protection.

Thank you,
Peter

**Comment by markh794** [comment]
Just reading up on "4.9 Logical block protection" of the IBM LTO SCSI Reference provided earlier.
mhVTL does not currently support Logical block protection - but it looks like a cool thing to add. A 4 byte CRC to the payload as it is transferred across between Initiator<->target. The problem I will have is an application which generates this payload - so I can verify functionality.

**Comment by daaazdddi** [comment]
The only opensource software that supports it that I can think of is Cern's Castor system I remember some code there that shutdown the LBP feature when using MHVTL as the output. Spectrum protect has the feature along with arcserve and Xendata but would probably need a trail licence to install.

**Comment by markh794** [comment]
> Actually, I was able to try out the patch. I created a tape volume without block protection. I wrote several files to the tape. When I ran a tool we use to verify the tape, I got error output which showed a problem with the last file. However, this was the same behavior seen when using real tape. I think we have an issue with our application. When I tried verifying a tape on a system without your patch, I got different error output which indicated that none of the files could be verified and that there were I/O errors. So I think your new code may be working properly. I will be able to do more tests once we fix some issues on our end.
> 
> But I am still wondering if mhvtl provides support for block protection.
> 
> Thank you, Peter

Hi Peter,

Any chance of checking out the new issue I opened regarding support for Logical Block Protection. I'm hoping you have access to some hardware so I can verify I've seeded the CRC32C function correctly so the CRC matches what the application is generating.

Many thanks,
Mark

**Comment by rohr22** [comment]
Hi, Mark.

I'll try to ask some of my colleagues about this tomorrow.

Thank you,
Peter

P.S. Did you see my email with the subject "Fwd: mhvtl license"? Our legal
team says we can send you the code we have for block protection if you
agree to put some copyright notice in the source code.

**Comment by markh794** [comment]
Hi Peter,

Thanks for this.

Re: LBP code.
Thanks for following this up. I'm having fun trying it myself. I think I'm almost done - so I'll see how my mods go and determine if I'll add the additional license and use your code.

**Comment by markh794** [comment]
Based on CRC test utility in CASTOR s/w, I think I have both CRC32C and Reed-Solomon CRC implemented correctly.
I have just submitted 7 patches to include support for Data Integrity Validation.
Based on my reading of the IBM Ultrium LTO9 documentation, LTO5 & LTO6 will support RS-CRC, while LTO-7 & LTO8 support both RS-CRC and CRC32C.
I'll add DIV support to the T10k drives shortly.

**Comment by markh794** [comment]
Closing this out as nobody has raised issues with the feature.
