### ISSUE TITLE
Fix removal of flush_kernel_dcache_page() in v5.15 linux kernel

### ISSUE THREAD

**Issue by gonzoleeman** [markh794/mhvtl#77]
Commit:

> f358afc52c30 mm: remove flush_kernel_dcache_page

Removed flush_kernel_dcache_page(). It's not clear how it should be replaced. Some of the arch-es replaced it with flush_kernel_dcache_page_addr(page_address(ARG)), but that's not export.

This will cause the mhvtl kernel module build to fail for newer kernels.

Another good time to suggest architecting this in a way that allows upstreaming of your kernel module.

**Comment by markh794** [comment]
I wonder how hard it would be to graft onto virtio_scsi ?
virtio can use LIO as a backend, so the other option would be to add into LIO user space.. Every time I look at LIO user space, my head starts to hurt - I can't seem to get past cmake.. Do I try and take the LIO 'template' across into mhVTL, or move mhVTL user across into LIO..
At least this 'flush_kernel_dcache_page' doesn't look to be a major change - e.g. a "sed -i 's/flush_kernel_dcache_page/flush_dcache_page/g' kernel/fetch50.c" should do the trick. Let me test a little bit.
Might also look at what they did in the sg driver (as that is where I keep lifting the functions from).

**Comment by gonzoleeman** [comment]
the fix seems to be working. Tested on v5.16 kernel on openSUSE Tumbleweed as well as a few older kernels.

**Comment by gonzoleeman** [comment]
Closing this issue.
