### ISSUE TITLE
Support for Logical Block Protection

### ISSUE THREAD

**Issue by markh794** [markh794/mhvtl#79]
Add support for LBP for Ultrium 7 & 8 and STK T10000

**Comment by markh794** [comment]
Initial work is underway - CRC32C on the read path appears to be working, however needs confirmation.

Does anybody have real hardware I could obtain a couple of examples of the CRC32C ?

**Comment by markh794** [comment]
I may as well ask for the Reed-solomon CRC at the same time.

Does anybody have real hardware I could obtain a couple of examples of the Reed-Solomon CRC ?

Setup Reed-Solomon CRC on an IBM Ultrium LTO-7 or LTO-8 drive.
`# sg_wr_mode -p 0x0a,0xf0 -d -c 0a,f0,00,1c,1,4,c0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /dev/sg10`

Where '/dev/sg10' is the path to the drive in question.

Then dd in a block of data (including LBP).
e.g.
`# dd if=/dev/st0 of=/tmp/b1-rscrc bs=65540 count=1` (assuming a 64k block) - adjust the 'bs=' to the block size + 4

A copy of the '/tmp/b1-rscrc' file would be most welcome.

**Comment by markh794** [comment]
And another request :

`sg_inq --hex --page=0xb5 /dev/sg12`
 (where /dev/sg12 is the sg path to the drive in question - hint: `lsscsi -g`)

**Comment by markh794** [comment]
Based on CRC test utility in CASTOR s/w, I think I have both CRC32C and Reed-Solomon CRC implemented correctly.
I have just submitted 7 patches to include support for Data Integrity Validation.
Based on my reading of the IBM Ultrium LTO9 documentation, LTO5 & LTO6 will support RS-CRC, while LTO-7 & LTO8 support both RS-CRC and CRC32C.
I'll add DIV support to the T10k drives shortly.

**Comment by rohr22** [comment]
I updated our code to bypass the check for protection and our software failed to write to a virtual tape which was set up to use block protection. I saw this logged in /var/log/messages when the error occurred:

Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: ssc_mode_select(): Setting LBP method: 1, LBP length: 4, LBP_W: True, LBP_R: True
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: update_logical_block_protection(): +++ entry +++
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: lookup_pcode(): Looking for: Page/subpage (0a/f0)
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: lookup_pcode(): Found "Control Data Protection" -> Page/subpage (0a/f0)
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: update_logical_block_protection(): l: 0x638060, m: 0x1d56360, m->pcodePointer: 0x1d563a0
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: update_logical_block_protection(): Updating Logical Block Protection: Method: 0x01, LBP_R: True, LPB_W: True
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: completeSCSICommand(): OP s/n: (1365), sz: 34, sam_status: 0
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: CDB (1366) (delay 2805): 34 00 00 00 00 00 00 00 00 00
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: ssc_read_position(): READ POSITION (1366) **
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: ssc_read_position(): service_action: 0
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: resp_read_position(): Positioned at block 2
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: completeSCSICommand(): OP s/n: (1366), sz: 20, sam_status: 0
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: CDB (1367) (delay 805): 0a 00 00 00 54 00
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: ssc_write_6(): ssc_write_6(): 1 block of 84 bytes (1367) **
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: retrieve_CDB_data(): retrieving 84 bytes from kernel
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: check_restrictions(): returning: writable
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: writeBlock(): LBP on write - CRC type is RS-CRC
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: get_lbp_crc(): Reed-Solomon CRC check
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: ERROR: get_lbp_crc(): Reed-Solomon CRC mismatch - LBP: 0x538ab5e0, calculated: 0x83ec69fb
Jan  5 14:08:13 choctaw /usr/bin/vtltape[955]: ERROR: writeBlock_lzo(): LBP mis-compare on write

Is there something else I should report from the log file?

**Comment by markh794** [comment]
Thanks for the information. Not quite what I was hoping for, but still.. The RS-CRC routine was taken straight from the IBM SCSI reference guide. Oh well.
Now to a) Fix the Inquiry page for the 'protect=1' - should be a very simple fix. and b) modify the write so it actually writes the block of data but returns the error. This way, I'll be able to obtain a copy of the virtual media and figure out the correct seeding required to get the RS-CRC to match the data the application sent.

**Comment by markh794** [comment]
Two patches just submitted. The first one addresses the standard SCSI Inquiry 'protect' bit.
The 2nd patch changes the behaviour so the block of data is written before the CRC check.
Please apply the two patches, re-try your application/test routine. It will (should) fail as I've not modified anything within the RS-CRC routine yet. Then share the syslog *and* the virtual media contents (simply tar up the /opt/mhvtl/<barcode> directory in question).

**Comment by rohr22** [comment]
I tried the latest code and I am still seeing PROTECT=0:

```
# sg_inq /dev/sg15
standard INQUIRY:
  PQual=0  Device_type=8  RMB=1  version=0x05  [SPC-3]
  [AERC=0]  [TrmTsk=0]  NormACA=0  HiSUP=0  Resp_data_format=2
  SCCS=0  ACC=0  TPGS=0  3PC=0  Protect=0  [BQue=0]
  EncServ=0  MultiP=0  [MChngr=0]  [ACKREQQ=0]  Addr16=1
  [RelAdr=0]  WBus16=1  Sync=0  Linked=0  [TranDis=0]  CmdQue=0
  [SPI: Clocking=0x0  QAS=0  IUS=0]
    length=72 (0x48)   Peripheral device type: medium changer
 Vendor identification: IBM     
 Product identification: 3584            
 Product revision level: 0106
 Unit serial number: XYZZY_A   
```

I updated the etc/generate_device_conf.in file to have this for the add_library_contents_10 function:

```
add_library_contents_10()
{
        if (( $# != 0 )) ; then
                echo "internal error: expected 0 arguments, got $#" 1>&2
                exit 1
        fi

        #         index channel target LUN Vendor ProdID ProdRev S/No
        add_library 10 0 0 0 "IBM" "3584"  "550V"  "XYZZY_A"
        #         index channel target LUN S/No Lib# Slot
        add_ibm_ultrium_5_drive 11 0 1 0 "XYZZY_A1" 10 1
        add_ibm_ultrium_5_drive 12 0 2 0 "XYZZY_A2" 10 2
        add_ibm_ultrium_5_drive 13 0 3 0 "XYZZY_A3" 10 3
        add_ibm_ultrium_5_drive 14 0 4 0 "XYZZY_A4" 10 4
        add_ibm_ultrium_5_drive 15 0 5 0 "XYZZY_A5" 10 5
        add_ibm_ultrium_5_drive 16 0 6 0 "XYZZY_A6" 10 6
        add_ibm_ultrium_5_drive 17 0 7 0 "XYZZY_A7" 10 7
        add_ibm_ultrium_5_drive 18 0 8 0 "XYZZY_A8" 10 8
        add_ibm_ultrium_5_drive 19 0 9 0 "XYZZY_A9" 10 9
        add_ibm_ultrium_5_drive 20 0 10 0 "XYZZY_AA" 10 10
}

```
The one from you has:
```
add_library_contents_10()
{
        if (( $# != 0 )) ; then
                echo "internal error: expected 0 arguments, got $#" 1>&2
                exit 1
        fi

        #         index channel target LUN Vendor ProdID ProdRev S/No
        add_library 10 0 0 0 "STK" "L700"  "550V"  "XYZZY_A"
        #         index channel target LUN S/No Lib# Slot
        add_ibm_ultrium_5_drive 11 0 1 0 "XYZZY_A1" 10 1
        add_ibm_ultrium_5_drive 12 0 2 0 "XYZZY_A2" 10 2
        add_ibm_ultrium_4_drive 13 0 3 0 "XYZZY_A3" 10 3
        add_ibm_ultrium_4_drive 14 0 4 0 "XYZZY_A4" 10 4
}


```
Could that be an issue?

**Comment by rohr22** [comment]
Mark, I have the other information you asked for:

> Then share the syslog and the virtual media contents (simply tar up the /opt/mhvtl/<barcode> directory in question).

I was wondering if you need all three of the barcode files - indx, data, and meta. Or would just the indx and meta files be sufficient? Attached is the syslog information:

[for_mark.tar.gz](https://github.com/markh794/mhvtl/files/7818831/for_mark.tar.gz)

**Comment by markh794** [comment]
I would need all three files - as the data is compressed, I need to know the original size of the block along with recorded CRC32C (I could figure it out, but it will be easier if I get all the data). I certainly need the 'data' file as I need this as the reference to run some RS-CRC against until I get the matching CRCs.

The default LTO4 & LTO5 do not support the LBP - you need to update the /etc/mhvtl/device.conf to reflect LTO6 thru 8 (your choice). My reading of the IBM SCSI reference is that LTO-4 & LTO-5 do not support LBP.

**Comment by rohr22** [comment]
I updated the /etc/mhvtl/device.conf to have this:
```

Library: 10 CHANNEL: 00 TARGET: 00 LUN: 00
 Vendor identification: IBM
 Product identification: 3584
 Unit serial number: XYZZY_A
 NAA: 10:22:33:44:ab:00:00:00
 Home directory: /opt/vtl
 PERSIST: False
 Backoff: 400


Drive: 11 CHANNEL: 00 TARGET: 01 LUN: 00
 Library ID: 10 Slot: 01
 Vendor identification: IBM
 Product identification: ULT3580-TD6
 Unit serial number: XYZZY_A1
 NAA: 10:22:33:44:ab:00:01:00
 Compression: factor 1 enabled 1
 Compression type: lzo
 Backoff: 400
```

but I am still seeing PROTECT=0 from the sg_inq command.

**Comment by markh794** [comment]
A couple more patches..
The last one "should" permit RS-CRC to succeed - I was seeding the function differently to my test routine.
One patch logs the drives supported features at initialisation time - will hopefully identify why protect=0 is being reported.

**Comment by markh794** [comment]
Closing this out as working based on discussions with regards to patch : 3b447faaadcf9295655990a524364723e6e372b7
FWIW (for anybody reading this thread) - the protect=0 was due to query against library device not drive.

**Comment by markh794** [comment]
Closing this out as working based on discussions with regards to patch : 3b447fa
FWIW (for anybody reading this thread) - the protect=0 was due to query against library device not drive.
