### ISSUE TITLE
mhvtl 1.5.4 kernel crashes on IBM ppc64 machines

### ISSUE THREAD

**Issue by rohr22** [markh794/mhvtl#8]
[quiznos-build2_mhvtl_kernel_crash_vmcore-dmesg.txt](https://github.com/markh794/mhvtl/files/906432/quiznos-build2_mhvtl_kernel_crash_vmcore-dmesg.txt)

We have been experiencing frequent mhvtl kernel crashes on our IBM ppc64 systems. Attached is a kernel crash vmcore-dmesg.txt file.

The 'crash vmcore /usr/lib/debug/lib/modules/3.10.0-327.el7.ppc64le/vmlinux' output shows:
      KERNEL: /usr/lib/debug/lib/modules/3.10.0-327.el7.ppc64le/vmlinux
    DUMPFILE: vmcore  [PARTIAL DUMP]
        CPUS: 512
        DATE: Wed Mar 15 23:32:00 2017
      UPTIME: 7 days, 09:33:44
LOAD AVERAGE: 0.00, 0.01, 0.05
       TASKS: 5274
    NODENAME: quiznos-build2
     RELEASE: 3.10.0-327.el7.ppc64le
     VERSION: #1 SMP Thu Oct 29 17:31:13 EDT 2015
     MACHINE: ppc64le  (3026 Mhz)
      MEMORY: 37 GB
       PANIC: "Unable to handle kernel paging request for data at address 0xffffffffffffff70"
         PID: 11978
     COMMAND: "vtltape"
        TASK: c0000001662e7200  [THREAD_INFO: c000000166378000]
         CPU: 501
       STATE: TASK_RUNNING (PANIC)

Does anyone have any ideas of what is wrong?

Thank you,
Peter

**Comment by markh794** [comment]
Bug open for close to 3 years..
Recently gained access to PPC lab - this appears to have fixed the race condition.

commit 253ee233443be3c56ed733999672bf4764957328
Author: Mark Harvey <markh794@gmail.com>
Date:   Mon Mar 2 16:47:00 2020 +1100
