### ISSUE TITLE
Logical block protection issues with IBM LTO-7 and LTO-8

### ISSUE THREAD

**Issue by rohr22** [markh794/mhvtl#81]
Hi, Mark. It seems like the block protection functionality is working well for IBM LTO-6 drives. However, I am having issues when trying to use IBM LTO-7 or IBM LTO-8 drives. I am getting errors like this:

Jan 10 11:43:14 choctaw /usr/bin/vtltape[10349]: ERROR: get_lbp_crc(): CRC32C mismatch - LBP: 0x85f82ccd, calculated: 0xcd2cf885
Jan 10 11:43:14 choctaw /usr/bin/vtltape[10349]: ERROR: writeBlock_lzo(): LBP mis-compare on write : Returning E_LOGICAL_BLOCK_GUARD_FAILED

Our software is detecting an EOM (end of media) and nothing is getting written to the tape. I tried doing a test without logical block protection enabled and I was able to write to an LTO-7 tape. I have attached the vtl log entries from /var/log/messages as well as the generate_device_conf.in and generate_library_contents.in that I used.

[lto7_lto8_lbp_failure.tar.gz](https://github.com/markh794/mhvtl/files/7841005/lto7_lto8_lbp_failure.tar.gz)

**Comment by markh794** [comment]
Are you able to share the virtual media with me ?
The write did occur (for this use case). I will need all files. 
The other option is to create a utility that will report various CRC32C seeding options

**Comment by rohr22** [comment]
> The other option is to create a utility that will report various CRC32C seeding options


What do you have in mind for this?

**Comment by markh794** [comment]
Hi Peter,
I've just pushed a patch which will log the CRC using the following combinations:
+ Seed using values of '0' and '0xffffffff'
+ Returned value, and returned value bit inverted.

Can you apply the patch and 're-crash the car' (reproduce the write) and provide the /var/log/messages.
Thanks

**Comment by rohr22** [comment]
OK, I applied your patch and recreated the problem. Attached is a tar file with vtl entries from when the problem occurred.

[lto7_failure2.tar.gz](https://github.com/markh794/mhvtl/files/7843171/lto7_failure2.tar.gz)

Thank you,
Peter

**Comment by markh794** [comment]
thanks for the log..

`
Jan 10 20:14:03 choctaw /usr/bin/vtltape[7093]: ERROR: get_lbp_crc(): CRC32C mismatch - LBP: 0xcc1e58d7, calculated: 0xd7581ecc
Jan 10 20:14:03 choctaw /usr/bin/vtltape[7093]: ERROR: writeBlock_lzo(): LBP mis-compare on write : Returning E_LOGICAL_BLOCK_GUARD_FAILED
Jan 10 20:14:03 choctaw /usr/bin/vtltape[7093]: return_sense(): [Key/ASC/ASCQ] [04 10 01]
Jan 10 20:14:03 choctaw /usr/bin/vtltape[7093]: ERROR: log_crc_options(): Legacy CRC32C: 0xd7581ecc
Jan 10 20:14:03 choctaw /usr/bin/vtltape[7093]: ERROR: log_crc_options(): CRC32C with seed 0: 0xd7581ecc
Jan 10 20:14:03 choctaw /usr/bin/vtltape[7093]: ERROR: log_crc_options(): Inverted CRC32C with seed 0: 0x28a7e133
Jan 10 20:14:03 choctaw /usr/bin/vtltape[7093]: ERROR: log_crc_options(): CRC32C with seed 0xffffffff: 0x0892032f
Jan 10 20:14:03 choctaw /usr/bin/vtltape[7093]: ERROR: log_crc_options(): Inverted CRC32C with seed 0xffffffff: 0xf76dfcd0
`

Took me a little while staring at it to realise it's a big-endian/little-endian thing. I didn't need that additional debugging Information after all.

e.g.
`ERROR: get_lbp_crc(): CRC32C mismatch - LBP: 0xcc1e58d7, calculated: 0xd7581ecc`

I'll hopefully get a fix out ASAP.

**Comment by rohr22** [comment]
> Took me a little while staring at it to realise it's a big-endian/little-endian thing. I didn't need that additional debugging Information after all.

Good. I wonder why it doesn't occur with LTO-6 tapes.

**Comment by markh794** [comment]
LTO-6 only use RS-CRC - that routine I coped from the IBM SCSI reference manual appendix. It returns the RS-CRC value in big-end order.

**Comment by markh794** [comment]
uploaded patch 5837bb924f1e9e54d9b83cb2e383777e12ed7f7b - untested, but should fix the CRC32C bug.

**Comment by rohr22** [comment]
This seems to fix the problem. I can now write to tape with logical block protection with IBM LTO-6, LTO-7, and LTO-8!

Thank you.

**Comment by markh794** [comment]
Closing this out. Thanks for the verification.
