### ISSUE TITLE
dump_tape and preload_tape are exactly the same binary so why build both?

### ISSUE THREAD

**Issue by gonzoleeman** [markh794/mhvtl#84]
It seems the new dump_tape binary uses exactly the same code as the preload_tape binary. I realize the binary behaves differently using one name or the other, but do we really need to compile both of these? My build service actually complains that these two are identical, so why in the heck aren't I using a link instead of building both?

It would be simple to submit a fix that just links preload_tape to dump_tape, if you would entertain such an optimization. While I was at it, I might combine the two man pages, as well, for bonus points.

**Comment by markh794** [comment]
Gladly accept a patch to link them. It was always my intention, however slipped my mind to complete

**Comment by gonzoleeman** [comment]
See pull request #85

**Comment by markh794** [comment]
Thanks - commit pull request.
