### ISSUE TITLE
Variables in make recursion wrong (sometimes)?

### ISSUE THREAD

**Issue by melak** [markh794/mhvtl#88]
I have been staring at this for a couple of months now and could not decide whether it's actually wrong or I've gone mad. I am not a make wizard by any stretch of the imagination, though I'd like to think I have the fundamentals about right.

The Makefiles (the top-level one, I don't think the others are affected), when doing recursion, use a construct like this (at least in the `install` target):
```
$(MAKE) -C usr install $(LIBDIR) $(PREFIX) $(DESTDIR) $(SYSTEMD_SERVICE_DIR)
```
The intent is obvious, but I don't think this means what the intent was - that would have been
```
$(MAKE) -C usr install LIBDIR=$(LIBDIR) PREFIX=$(PREFIX) DESTDIR=$(DESTDIR) SYSTEMD_SERVICE_DIR=$(SYSTEMD_SERVICE_DIR)
```
as it is correctly used in a couple of other places.

Since the subdir Makefiles have declarations along the lines of `PREFIX ?= /usr/local`, until one _actually_ tries to install mhVTL to a different directory (or whatever else the variables control), it does not become very apparent that the Makefile doesn't quite work as intended.

Have I gone mad?

**Comment by gonzoleeman** [comment]
> On Feb 18, 2022, at 3:23 AM, melak ***@***.***> wrote:
> 
> 
> I have been staring at this for a couple of months now and could not decide whether it's actually wrong or I've gone mad. I am not a make wizard by any stretch of the imagination, though I'd like to think I have the fundamentals about right.
> 
> The Makefiles (the top-level one, I don't think the others are affected), when doing recursion, use a construct like this (at least in the install target):
> 
> $(MAKE) -C usr install $(LIBDIR) $(PREFIX) $(DESTDIR) $(SYSTEMD_SERVICE_DIR)
> The intent is obvious, but I don't think this means what the intent was - that would have been
> 
> $(MAKE) -C usr install LIBDIR=$(LIBDIR) PREFIX=$(PREFIX) DESTDIR=$(DESTDIR) SYSTEMD_SERVICE_DIR=$(SYSTEMD_SERVICE_DIR)
> as it is correctly used in a couple of other places.
> 
> Since the subdir Makefiles have declarations along the lines of PREFIX ?= /usr/local, until one actually tries to install mhVTL to a different directory (or whatever else the variables control), it does not become very apparent that the Makefile doesn't quite work as intended.
> 
> Have I gone mad?
> 
> 

No, probably not. :)

I think almost all of those recursive make calls got it wrong, but it isn’t normally noticed.

I have some of those fixed in my branch (for my distribution), but haven’t submitted them yet. :(

—
Lee Duncan
