### ISSUE TITLE
unload is asynchronous

### ISSUE THREAD

**Issue by nichenke** [markh794/mhvtl#9]
We ran into a problem with rapid load/unload cycles on a drive. We'd rather quicky hit a 'HARDWARE ERROR' with 'manual intervention required'.

A quick investigation showed syslog interleaving the finishing of the previous unload with the next load.  It looks like adding a `check_tape_unload` and calling it in `move_drive2slot` here: https://github.com/markh794/mhvtl/blob/7a78a571dc25528ede3dc7fbc47310a546ad3c50/usr/smc.c#L1253 like `move_slot2drive` does for the load side, making sure we get the 'ejected' message back from vtltape before considering the move complete.

If this solution seems workable, pushing a change is easy enough. Part of filing the issue is to make sure we aren't missing a SCSI command or something else for driving rapid load/unload cycles like this.

A reproducer script, assuming a robot at /dev/sg7.
```
#!/bin/bash

set -e -o pipefail
set -x

for i in $(seq 0 10); do
        logger "loop $i"
        sg_inq /dev/sg7
        sg_modes --verbose --six /dev/sg7
        logger "loading tape"
        sg_raw -v /dev/sg7 a5 00 00 01 10 00 01 00 00 00 00 00
        logger "unloading tape"
        sg_raw -v /dev/sg7 a5 00 00 01 01 00 10 00 00 00 00 00
        logger "unload finished"
done
```

**Comment by markh794** [comment]
Thanks for the bug report

**Comment by markh794** [comment]
commit cbbe7d47f538bccd2aa7e24219a9b19da539a064 should fix this.
