### ISSUE TITLE
device-conf-gen: fopen() failure not handled correctly

### ISSUE THREAD

**Issue by melak** [markh794/mhvtl#92]
https://github.com/markh794/mhvtl/blob/88816cd3e89d9864947e8d93bb32e07813b7bda1/usr/mhvtl-device-conf-generator.c#L181
@gonzoleeman is this really supposed to fall through if the config file cannot be opened?

**Comment by markh794** [comment]
Many thanks for the code review / sanity check. Appreciate the effort.
This seems like a very rare condition.
So my take on it is to "throw the baby out with the baby water" and abort(). Lets not die quietly.

**Comment by gonzoleeman** [comment]
Thanks for fixing! 

--
Lee-Man Duncan

**Comment by melak** [comment]
Thanks for fixing indeed. I concur that this happening must have been an unconventional setup to begin with (I should know, I have one :), but _if_ it happens, it's extremely hard to debug (don't ask how I know :).

Turns out this commit is only half the story though. I will be submitting a PR with some amendments to this shortly.
