### ISSUE TITLE
edit_tape function asks for -b flag, but doesn't accept it as an argument

### ISSUE THREAD

**Issue by dabiged** [markh794/mhvtl#98]
The edit_tape helpdoc states:
```
Please supply a barcode (-b barcode)

Usage: edit_tape -l lib -m PCL [-s size] [-t type] [-d density] [-w on|off]
       Where 'size' is in Megabytes
             'lib' is Library number
             'type' is data | clean | WORM
             'PCL' is Physical Cartridge Label (barcode)
             '-w on|off' enable/disable write protect flag
             'density' can be on of the following:
```
The first line (from line 188 of edit_tape) implies that the cartridge label should be passed with  -b flag, but edit_tape does not accept this.

Is the -b flag designed to allow the renaming of virtual tapes, or is this just a typo?

**Comment by markh794** [comment]
Many thanks for the bug report. I'll look into this as soon as possible.
I did go through the auxiliary utilities and thought I'd made all the options consistent. (-b <barcode>, -p <PCL>, -f <barcode (file)>.
Looks like I've missed at least one :)

**Comment by markh794** [comment]
oops.. the patch never made it from a private repo into this one..
561d4d5b473f29c44961cd4a64c2ff3e0c02ed2c has now been pushed.
Thanks for the bug report.
